# ===================================================================
#  CORE: App Service
# ===================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-svc
spec:
  type: ClusterIP
  ports: [{ port: 3001, targetPort: 3001 }]
  selector: { app: app-service }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: { app: app-service }
  template:
    metadata:
      labels: { app: app-service }
    spec:
      initContainers:
        - name: wait-for-kafka
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              BROKER="kafka-svc:9092"
              echo "Waiting for Kafka broker ($BROKER) to be available..."
              # FIX: Only wait for the broker to be reachable, not for a specific topic to exist.
              until /opt/kafka/bin/kafka-topics.sh --bootstrap-server $BROKER --list 2>/dev/null; do
                echo "Kafka broker not ready. Retrying in 2 seconds..."
                sleep 2
              done
              echo "Kafka broker is ready."
        - name: wait-for-notification
          image: busybox:1.36
          command:
            - sh
            - -c
            - 'until nc -z notification-service-svc 9999; do echo "waiting for notification"; sleep 2; done;'
      containers:
        - name: app-service
          image: d33102/app-service-svc:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3001 }]
          envFrom: [{ secretRef: { name: app-service-secret } }]
