# ===================================================================
#  CORE: Auth Service
# ===================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
spec:
  type: ClusterIP
  ports: [{ port: 8082, targetPort: 8082 }]
  selector: { app: auth-service }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      initContainers:
        - name: wait-for-user-service
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z user-service-svc 8081; do echo "waiting for user-service"; sleep 2; done;',
            ]
        - name: wait-for-redis
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z redis-svc 6379; do echo "waiting for redis"; sleep 2; done;',
            ]
      containers:
        - name: auth-service
          image: d33102/auth-service-svc:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8082 }]
          envFrom: [{ secretRef: { name: auth-service-secret } }]
