# ===================================================================
#  CORE: User Service
# ===================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  type: ClusterIP
  ports: [{ port: 8081, targetPort: 8081 }]
  selector: { app: user-service }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-service }
  template:
    metadata:
      labels: { app: user-service }
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z postgres-svc 5432; do echo "waiting for postgres"; sleep 2; done;',
            ]
        - name: wait-for-redis
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z redis-svc 6379; do echo "waiting for redis"; sleep 2; done;',
            ]
      containers:
        - name: user-service
          image: d33102/user-service-svc:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8081 }]
          envFrom: [{ secretRef: { name: user-service-secret } }]
